# SPDX-License-Identifier: CC0-1.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/klieret/jekyll-relative-url-check
    rev: v2.0.2
    hooks:
      - id: jekyll-relative-url-check-html
      - id: jekyll-relative-url-check-markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
      - id: markdownlint-fix

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.10.0
    hooks:
        - id: commitlint
          stages: [commit-msg]
          additional_dependencies:
            - '@commitlint/config-conventional'
