repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/klieret/jekyll-relative-url-check
    rev: v2.0.1
    hooks:
    -   id: jekyll-relative-url-check-html
    -   id: jekyll-relative-url-check-markdown
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.0
    hooks:
    - id: markdownlint
    - id: markdownlint-fix
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.8.0
    hooks:
    -   id: eslint
        additional_dependencies:
        -   'eslint'
        -   'standard'
        -   'eslint-config-standard'
        -   'eslint-plugin-import'
        -   'eslint-plugin-node'
        -   'eslint-plugin-promise'
        args: ['--fix']
