# SPDX-License-Identifier: CC0-1.0
# Setup
title: Samuel Wu
tagline: >-
  We cannot know, and will never know... But in the shadows of the unknown,
  truth will prevail.
description: >-
  A site for Samuel's blog which includes programming, technology, media,
  politics, etc.
url: https://twopizza9621536.github.io
baseurl: ""

# Repository
repository: TwoPizza9621536/twopizza9621536.github.io
origin: https://github.com/TwoPizza9621536/twopizza9621536.github.io.git

# Timezone and Locale
encoding: utf-8
timezone: America/New_York
locale: en-US
lang: en-US

# About/Contact
author:
  name: Samuel Wu
  url: https://github.com/TwoPizza9621536
  email: twopizza9621536@gmail.com
  twitter:
    username: TwoPizza9621536
    card: summary

socials:
  - https://social.restless.systems/@TwoPizza9621536
  - https://github.com/TwoPizza9621536
  - https://steamcommunity.com/profiles/76561199040648119/

# SEO
webmaster_verifications:
  google: I7yhE_OKyT8UlfvQvfF9KQqu0rZRZcaMZ9Y5nQhGyQ8

# Permalinks
collections_dir: collections
permalink: /:year/:title

# Pagination
pagination:
  enabled: true
  per_page: 10

# Archives
jekyll-archives:
  enabled:
    - year
    - tags
    - categories
  layouts:
    year: year-archive
  permalinks:
    year: /:year/
    tags: /:tags/
    categories: /:categories/

# Set Page Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# Markdown
kramdown:
  auto_ids: true
  line_width: 80
  toc_levels: 1..6

# Assets
sass:
  implementation: sass-embedded
  style: compressed

# Feeds
feed:
  excerpt_only: true

# Mentions
jekyll-mentions: https://github.com

# Make sure there are no YAML syntax errors
strict_front_matter: true

# New window for external links
external_links:
  enabled: true
  rel: external nofollow noopener noreferrer

# Latent Semantic Indexer
lsi: true

# Redirect
redirect_from:
  json: false

# Excluding Files
exclude:
  - LICENSE
  - LICENSES
  - README.md
  - frontmatter.json
