# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Samuel Wu @TwoPizza9621536
email: twopizza9621536@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This my blogs for coding, programming, technology, and software that will go
  into shenanigans. Keep scrolling to see my github profile.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://twopizza9621536.github.io"
twitter_username: TwoPizza9621536
github_username: TwoPizza9621536

repository: twopizza9621536/twopizza9621536.github.io
origin: https://github.com/TwoPizza9621536/twopizza9621536.github.io.git

encoding: UTF-8
timezone: America/New_York

# Pagination
permalink: /blogs/:year/:month/:day/:title/
pagination:
  enabled: true
  per_page: 3
  permalink: "/blogs/page:num/"
  title: " - page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true

# Archive
jekyll-archives:
  enabled:
    - year
    - month
    - day
  layout: archive

# AutoPages
autopages:
  enabled: true
  categories:
    title: 'Posts in category :cat'
  tags:
    title: 'Posts tagged with :tag'
  collections:
    title: 'Posts in collection :coll'

# Authors
collections_dir: collections
collections:
  mingw_gcc:
    label: "Quest for a MinGW GCC"
    output: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "mingw_gcc"
    values:
      layout: "post"

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-paginate-v2
  - jekyll-sass-converter
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-commonmark-ghpages
  - jekyll-mentions
  - jekyll-asciidoc
  - jekyll-toc
  - jekyll-email-protect
  - jekyll-archives
  - jekyll-last-modified-at
  - jekyll-include-cache
  - jekyll-octicons

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - CODE_OF_CONDUCT.md
  - renovate.json
  - vendor/

# Additional Flags
disable_disk_cache: true
lsi: true

sass:
  style: compressed

jekyll-mentions: https://twitter.com

last-modified-at:
  date-format: "%Y-%m-d %H:%ML%S %z"
